/*flexberryautogenerated="true"*/
namespace IIS.CodeReviewEngine
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class MetricValueL : BaseListForm<MetricValue>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public MetricValueL() : base(MetricValue.Views.MetricValueL)
        {
            EditPage = MetricValueE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/MetricValue/MetricValueL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
