<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="MetricValueE.aspx.cs" Inherits="IIS.CodeReviewEngine.MetricValueE" %>

<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-edit">
        <h2 class="ics-form-header ics-form-header-edit">Metric value</h2>
        <div class="ics-form-toolbar ics-form-toolbar-edit ics-sticky">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="ics-form-controls ics-form-controls-edit">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlDateLabel" runat="server" Text="Date" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlDate" runat="server"/>
</div>
<ac:Hinter ID="ctrlDateHint" runat="server" Title="Дата, когда метрика актуальна."/>
<asp:RequiredFieldValidator ID="ctrlDateValidator" runat="server" ControlToValidate="ctrlDate"
ErrorMessage="Не указано: Date" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlValueLabel" runat="server" Text="Value" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlValue" runat="server">
</asp:TextBox>

<ac:Hinter ID="ctrlValueHint" runat="server" Title="Значение метрики."/>
<asp:RequiredFieldValidator ID="ctrlValueValidator" runat="server" ControlToValidate="ctrlValue"
ErrorMessage="Не указано: Value" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlMetricLabel" runat="server" Text="Metric" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlMetric" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlMetricValidator" runat="server" ControlToValidate="ctrlMetric"
ErrorMessage="Не указано: Metric" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlMetric_NameLabel" runat="server" Text="Name" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlMetric_Name" runat="server" ReadOnly="true">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlMetric_NameValidator" runat="server" ControlToValidate="ctrlMetric_Name"
ErrorMessage="Не указано: Metric.Name" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTFSProjectLabel" runat="server" Text="T f s project" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlTFSProject" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlTFSProjectValidator" runat="server" ControlToValidate="ctrlTFSProject"
ErrorMessage="Не указано: TFSProject" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTFSProject_NameLabel" runat="server" Text="Name" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlTFSProject_Name" runat="server" ReadOnly="true">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlTFSProject_NameValidator" runat="server" ControlToValidate="ctrlTFSProject_Name"
ErrorMessage="Не указано: TFSProject.Name" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
