<%--flexberryautogenerated="true"--%>

<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="TFSProgrammerL.aspx.cs" Inherits="IIS.CodeReviewEngine.TFSProgrammerL" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-list">
        <h2 class="ics-form-header ics-header-listform">T f s programmer</h2>
        <div class="ics-form-controls ics-form-controls-list">
            <ac:WebObjectListView ID="WebObjectListView1" runat="server" Visible="true" />
        </div>
        <div>
            <asp:Label runat="server" ID="TeamProjectCollectionURLCaption">Team project collection URL</asp:Label>
            <asp:TextBox runat="server" ID="TeamProjectCollectionURL"></asp:TextBox>
            <asp:Button runat="server" ID="FillTFSUsers" OnClick="FillTFSUsers_OnClick" Text="Заполнить пользователями из TFS" />
            <asp:Label runat="server" ID="Console"></asp:Label>
        </div>
    </div>
</asp:Content>
