//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Значения метрик кода. По этому объекту данных будем строить графики.
    /// </summary>
    // *** Start programmer edit section *** (MetricValue CustomAttributes)

    // *** End programmer edit section *** (MetricValue CustomAttributes)
    [AutoAltered()]
    [Caption("Значение метрик кода")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MetricValueE", new string[] {
            "Date as \'Date\'",
            "Value as \'Value\'",
            "Metric as \'Metric\'",
            "Metric.Name as \'Name\'",
            "TFSProject as \'T f s project\'",
            "TFSProject.Name as \'Name\'"})]
    [View("MetricValueL", new string[] {
            "Date as \'Date\'",
            "Value as \'Value\'",
            "Metric.Name as \'Name\'",
            "TFSProject.Name as \'Name\'"})]
    public class MetricValue : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDate = System.DateTime.Now;
        
        private double fValue;
        
        private IIS.CodeReviewEngine.Metric fMetric;
        
        private IIS.CodeReviewEngine.TFSProject fTFSProject;
        
        // *** Start programmer edit section *** (MetricValue CustomMembers)

        // *** End programmer edit section *** (MetricValue CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (MetricValue.Date CustomAttributes)

        // *** End programmer edit section *** (MetricValue.Date CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (MetricValue.Date Get start)

                // *** End programmer edit section *** (MetricValue.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (MetricValue.Date Get end)

                // *** End programmer edit section *** (MetricValue.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MetricValue.Date Set start)

                // *** End programmer edit section *** (MetricValue.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (MetricValue.Date Set end)

                // *** End programmer edit section *** (MetricValue.Date Set end)
            }
        }
        
        /// <summary>
        /// Значение.
        /// </summary>
        // *** Start programmer edit section *** (MetricValue.Value CustomAttributes)

        // *** End programmer edit section *** (MetricValue.Value CustomAttributes)
        [NotNull()]
        public virtual double Value
        {
            get
            {
                // *** Start programmer edit section *** (MetricValue.Value Get start)

                // *** End programmer edit section *** (MetricValue.Value Get start)
                double result = this.fValue;
                // *** Start programmer edit section *** (MetricValue.Value Get end)

                // *** End programmer edit section *** (MetricValue.Value Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MetricValue.Value Set start)

                // *** End programmer edit section *** (MetricValue.Value Set start)
                this.fValue = value;
                // *** Start programmer edit section *** (MetricValue.Value Set end)

                // *** End programmer edit section *** (MetricValue.Value Set end)
            }
        }
        
        /// <summary>
        /// Значения метрик кода. По этому объекту данных будем строить графики.
        /// </summary>
        // *** Start programmer edit section *** (MetricValue.Metric CustomAttributes)

        // *** End programmer edit section *** (MetricValue.Metric CustomAttributes)
        [PropertyStorage(new string[] {
                "Metric"})]
        [NotNull()]
        public virtual IIS.CodeReviewEngine.Metric Metric
        {
            get
            {
                // *** Start programmer edit section *** (MetricValue.Metric Get start)

                // *** End programmer edit section *** (MetricValue.Metric Get start)
                IIS.CodeReviewEngine.Metric result = this.fMetric;
                // *** Start programmer edit section *** (MetricValue.Metric Get end)

                // *** End programmer edit section *** (MetricValue.Metric Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MetricValue.Metric Set start)

                // *** End programmer edit section *** (MetricValue.Metric Set start)
                this.fMetric = value;
                // *** Start programmer edit section *** (MetricValue.Metric Set end)

                // *** End programmer edit section *** (MetricValue.Metric Set end)
            }
        }
        
        /// <summary>
        /// Значения метрик кода. По этому объекту данных будем строить графики.
        /// </summary>
        // *** Start programmer edit section *** (MetricValue.TFSProject CustomAttributes)

        // *** End programmer edit section *** (MetricValue.TFSProject CustomAttributes)
        [PropertyStorage(new string[] {
                "TFSProject"})]
        [NotNull()]
        public virtual IIS.CodeReviewEngine.TFSProject TFSProject
        {
            get
            {
                // *** Start programmer edit section *** (MetricValue.TFSProject Get start)

                // *** End programmer edit section *** (MetricValue.TFSProject Get start)
                IIS.CodeReviewEngine.TFSProject result = this.fTFSProject;
                // *** Start programmer edit section *** (MetricValue.TFSProject Get end)

                // *** End programmer edit section *** (MetricValue.TFSProject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MetricValue.TFSProject Set start)

                // *** End programmer edit section *** (MetricValue.TFSProject Set start)
                this.fTFSProject = value;
                // *** Start programmer edit section *** (MetricValue.TFSProject Set end)

                // *** End programmer edit section *** (MetricValue.TFSProject Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MetricValueE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MetricValueE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MetricValueE", typeof(IIS.CodeReviewEngine.MetricValue));
                }
            }
            
            /// <summary>
            /// "MetricValueL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MetricValueL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MetricValueL", typeof(IIS.CodeReviewEngine.MetricValue));
                }
            }
        }
    }
}
