//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справочник метрик кода.
    /// </summary>
    // *** Start programmer edit section *** (Metric CustomAttributes)

    // *** End programmer edit section *** (Metric CustomAttributes)
    [AutoAltered()]
    [Caption("Метрика кода")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MetricE", new string[] {
            "Name as \'Name\'"})]
    [View("MetricL", new string[] {
            "Name as \'Name\'"})]
    public class Metric : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Metric CustomMembers)

        // *** End programmer edit section *** (Metric CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Metric.Name CustomAttributes)

        // *** End programmer edit section *** (Metric.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Metric.Name Get start)

                // *** End programmer edit section *** (Metric.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Metric.Name Get end)

                // *** End programmer edit section *** (Metric.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Metric.Name Set start)

                // *** End programmer edit section *** (Metric.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Metric.Name Set end)

                // *** End programmer edit section *** (Metric.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MetricE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MetricE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MetricE", typeof(IIS.CodeReviewEngine.Metric));
                }
            }
            
            /// <summary>
            /// "MetricL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MetricL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MetricL", typeof(IIS.CodeReviewEngine.Metric));
                }
            }
        }
    }
}
