//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверяющий программист.
    /// </summary>
    // *** Start programmer edit section *** (Reviewer CustomAttributes)

    // *** End programmer edit section *** (Reviewer CustomAttributes)
    [AutoAltered()]
    [Caption("Проверяющий")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ReviewerE", new string[] {
            "TFSProgrammer",
            "TFSProgrammer.Name",
            "TFSProgrammer.Login",
            "TFSProgrammer.Domain",
            "TeamSlice"}, Hidden=new string[] {
            "TFSProgrammer.Name",
            "TFSProgrammer.Login",
            "TFSProgrammer.Domain",
            "TeamSlice"})]
    [MasterViewDefineAttribute("ReviewerE", "TFSProgrammer", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Reviewer : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CodeReviewEngine.TFSProgrammer fTFSProgrammer;
        
        private IIS.CodeReviewEngine.TeamSlice fTeamSlice;
        
        // *** Start programmer edit section *** (Reviewer CustomMembers)

        // *** End programmer edit section *** (Reviewer CustomMembers)

        
        /// <summary>
        /// Проверяющий программист.
        /// </summary>
        // *** Start programmer edit section *** (Reviewer.TFSProgrammer CustomAttributes)

        // *** End programmer edit section *** (Reviewer.TFSProgrammer CustomAttributes)
        [PropertyStorage(new string[] {
                "Programmer"})]
        [NotNull()]
        public virtual IIS.CodeReviewEngine.TFSProgrammer TFSProgrammer
        {
            get
            {
                // *** Start programmer edit section *** (Reviewer.TFSProgrammer Get start)

                // *** End programmer edit section *** (Reviewer.TFSProgrammer Get start)
                IIS.CodeReviewEngine.TFSProgrammer result = this.fTFSProgrammer;
                // *** Start programmer edit section *** (Reviewer.TFSProgrammer Get end)

                // *** End programmer edit section *** (Reviewer.TFSProgrammer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Reviewer.TFSProgrammer Set start)

                // *** End programmer edit section *** (Reviewer.TFSProgrammer Set start)
                this.fTFSProgrammer = value;
                // *** Start programmer edit section *** (Reviewer.TFSProgrammer Set end)

                // *** End programmer edit section *** (Reviewer.TFSProgrammer Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CodeReviewEngine.TeamSlice.
        /// </summary>
        // *** Start programmer edit section *** (Reviewer.TeamSlice CustomAttributes)

        // *** End programmer edit section *** (Reviewer.TeamSlice CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TeamSlice"})]
        public virtual IIS.CodeReviewEngine.TeamSlice TeamSlice
        {
            get
            {
                // *** Start programmer edit section *** (Reviewer.TeamSlice Get start)

                // *** End programmer edit section *** (Reviewer.TeamSlice Get start)
                IIS.CodeReviewEngine.TeamSlice result = this.fTeamSlice;
                // *** Start programmer edit section *** (Reviewer.TeamSlice Get end)

                // *** End programmer edit section *** (Reviewer.TeamSlice Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Reviewer.TeamSlice Set start)

                // *** End programmer edit section *** (Reviewer.TeamSlice Set start)
                this.fTeamSlice = value;
                // *** Start programmer edit section *** (Reviewer.TeamSlice Set end)

                // *** End programmer edit section *** (Reviewer.TeamSlice Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ReviewerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ReviewerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReviewerE", typeof(IIS.CodeReviewEngine.Reviewer));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Reviewer.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfReviewer CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfReviewer CustomAttributes)
    public class DetailArrayOfReviewer : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CodeReviewEngine.DetailArrayOfReviewer members)

        // *** End programmer edit section *** (IIS.CodeReviewEngine.DetailArrayOfReviewer members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Reviewer by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Reviewer.
        /// </summary>
        public DetailArrayOfReviewer(IIS.CodeReviewEngine.TeamSlice fTeamSlice) : 
                base(typeof(Reviewer), ((ICSSoft.STORMNET.DataObject)(fTeamSlice)))
        {
        }
        
        public IIS.CodeReviewEngine.Reviewer this[int index]
        {
            get
            {
                return ((IIS.CodeReviewEngine.Reviewer)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CodeReviewEngine.Reviewer dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
