//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Интервал работы команды. Эта сущность задаёт правила, по которым формируется задание на проверку кода. Задаются временные границы и участники, которые должны выполнять проверку кода.
    /// </summary>
    // *** Start programmer edit section *** (TeamSlice CustomAttributes)

    // *** End programmer edit section *** (TeamSlice CustomAttributes)
    [AutoAltered()]
    [Caption("Интервал работы команды")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ProjectForReview", new string[0])]
    [View("TeamSliceE", new string[] {
            "StartDate as \'Start date\'",
            "EndDate as \'End date\'",
            "Team as \'Team\'"})]
    [AssociatedDetailViewAttribute("TeamSliceE", "Reviewers", "ReviewerE", true, "-Reviewers", "Reviewers", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("TeamSliceE", "Team", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("TeamSliceL", new string[] {
            "StartDate as \'Start date\'",
            "EndDate as \'End date\'",
            "Team.Name as \'Name\'"})]
    public class TeamSlice : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStartDate;
        
        private System.DateTime fEndDate;
        
        private IIS.CodeReviewEngine.Team fTeam;
        
        private IIS.CodeReviewEngine.DetailArrayOfReviewer fReviewers;
        
        // *** Start programmer edit section *** (TeamSlice CustomMembers)

        // *** End programmer edit section *** (TeamSlice CustomMembers)

        
        /// <summary>
        /// Начальная дата.
        /// </summary>
        // *** Start programmer edit section *** (TeamSlice.StartDate CustomAttributes)

        // *** End programmer edit section *** (TeamSlice.StartDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime StartDate
        {
            get
            {
                // *** Start programmer edit section *** (TeamSlice.StartDate Get start)

                // *** End programmer edit section *** (TeamSlice.StartDate Get start)
                System.DateTime result = this.fStartDate;
                // *** Start programmer edit section *** (TeamSlice.StartDate Get end)

                // *** End programmer edit section *** (TeamSlice.StartDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TeamSlice.StartDate Set start)

                // *** End programmer edit section *** (TeamSlice.StartDate Set start)
                this.fStartDate = value;
                // *** Start programmer edit section *** (TeamSlice.StartDate Set end)

                // *** End programmer edit section *** (TeamSlice.StartDate Set end)
            }
        }
        
        /// <summary>
        /// Конечная дата.
        /// </summary>
        // *** Start programmer edit section *** (TeamSlice.EndDate CustomAttributes)

        // *** End programmer edit section *** (TeamSlice.EndDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime EndDate
        {
            get
            {
                // *** Start programmer edit section *** (TeamSlice.EndDate Get start)

                // *** End programmer edit section *** (TeamSlice.EndDate Get start)
                System.DateTime result = this.fEndDate;
                // *** Start programmer edit section *** (TeamSlice.EndDate Get end)

                // *** End programmer edit section *** (TeamSlice.EndDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TeamSlice.EndDate Set start)

                // *** End programmer edit section *** (TeamSlice.EndDate Set start)
                this.fEndDate = value;
                // *** Start programmer edit section *** (TeamSlice.EndDate Set end)

                // *** End programmer edit section *** (TeamSlice.EndDate Set end)
            }
        }
        
        /// <summary>
        /// Интервал работы команды. Эта сущность задаёт правила, по которым формируется задание на проверку кода. Задаются временные границы и участники, которые должны выполнять проверку кода.
        /// </summary>
        // *** Start programmer edit section *** (TeamSlice.Team CustomAttributes)

        // *** End programmer edit section *** (TeamSlice.Team CustomAttributes)
        [PropertyStorage(new string[] {
                "Team"})]
        [NotNull()]
        public virtual IIS.CodeReviewEngine.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (TeamSlice.Team Get start)

                // *** End programmer edit section *** (TeamSlice.Team Get start)
                IIS.CodeReviewEngine.Team result = this.fTeam;
                // *** Start programmer edit section *** (TeamSlice.Team Get end)

                // *** End programmer edit section *** (TeamSlice.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TeamSlice.Team Set start)

                // *** End programmer edit section *** (TeamSlice.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (TeamSlice.Team Set end)

                // *** End programmer edit section *** (TeamSlice.Team Set end)
            }
        }
        
        /// <summary>
        /// Интервал работы команды. Эта сущность задаёт правила, по которым формируется задание на проверку кода. Задаются временные границы и участники, которые должны выполнять проверку кода.
        /// </summary>
        // *** Start programmer edit section *** (TeamSlice.Reviewers CustomAttributes)

        // *** End programmer edit section *** (TeamSlice.Reviewers CustomAttributes)
        public virtual IIS.CodeReviewEngine.DetailArrayOfReviewer Reviewers
        {
            get
            {
                // *** Start programmer edit section *** (TeamSlice.Reviewers Get start)

                // *** End programmer edit section *** (TeamSlice.Reviewers Get start)
                if ((this.fReviewers == null))
                {
                    this.fReviewers = new IIS.CodeReviewEngine.DetailArrayOfReviewer(this);
                }
                IIS.CodeReviewEngine.DetailArrayOfReviewer result = this.fReviewers;
                // *** Start programmer edit section *** (TeamSlice.Reviewers Get end)

                // *** End programmer edit section *** (TeamSlice.Reviewers Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TeamSlice.Reviewers Set start)

                // *** End programmer edit section *** (TeamSlice.Reviewers Set start)
                this.fReviewers = value;
                // *** Start programmer edit section *** (TeamSlice.Reviewers Set end)

                // *** End programmer edit section *** (TeamSlice.Reviewers Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ProjectForReview" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProjectForReview
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProjectForReview", typeof(IIS.CodeReviewEngine.TeamSlice));
                }
            }
            
            /// <summary>
            /// "TeamSliceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamSliceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamSliceE", typeof(IIS.CodeReviewEngine.TeamSlice));
                }
            }
            
            /// <summary>
            /// "TeamSliceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamSliceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamSliceL", typeof(IIS.CodeReviewEngine.TeamSlice));
                }
            }
        }
    }
}
