//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Команда разработчиков. Команда может работать одновременно с несколькими проектами в TFS.
    /// </summary>
    // *** Start programmer edit section *** (Team CustomAttributes)

    // *** End programmer edit section *** (Team CustomAttributes)
    [AutoAltered()]
    [Caption("Команда")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TeamE", new string[] {
            "Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("TeamE", "Projects", "TFSProjectForReviewE", true, "", "", true, new string[] {
            ""})]
    [View("TeamL", new string[] {
            "Name as \'Name\'"})]
    public class Team : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.CodeReviewEngine.DetailArrayOfTFSProjectForReview fProjects;
        
        // *** Start programmer edit section *** (Team CustomMembers)

        // *** End programmer edit section *** (Team CustomMembers)

        
        /// <summary>
        /// Название команды.
        /// </summary>
        // *** Start programmer edit section *** (Team.Name CustomAttributes)

        // *** End programmer edit section *** (Team.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Team.Name Get start)

                // *** End programmer edit section *** (Team.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Team.Name Get end)

                // *** End programmer edit section *** (Team.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.Name Set start)

                // *** End programmer edit section *** (Team.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Team.Name Set end)

                // *** End programmer edit section *** (Team.Name Set end)
            }
        }
        
        /// <summary>
        /// Команда разработчиков. Команда может работать одновременно с несколькими проектами в TFS.
        /// </summary>
        // *** Start programmer edit section *** (Team.Projects CustomAttributes)

        // *** End programmer edit section *** (Team.Projects CustomAttributes)
        public virtual IIS.CodeReviewEngine.DetailArrayOfTFSProjectForReview Projects
        {
            get
            {
                // *** Start programmer edit section *** (Team.Projects Get start)

                // *** End programmer edit section *** (Team.Projects Get start)
                if ((this.fProjects == null))
                {
                    this.fProjects = new IIS.CodeReviewEngine.DetailArrayOfTFSProjectForReview(this);
                }
                IIS.CodeReviewEngine.DetailArrayOfTFSProjectForReview result = this.fProjects;
                // *** Start programmer edit section *** (Team.Projects Get end)

                // *** End programmer edit section *** (Team.Projects Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.Projects Set start)

                // *** End programmer edit section *** (Team.Projects Set start)
                this.fProjects = value;
                // *** Start programmer edit section *** (Team.Projects Set end)

                // *** End programmer edit section *** (Team.Projects Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TeamE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamE", typeof(IIS.CodeReviewEngine.Team));
                }
            }
            
            /// <summary>
            /// "TeamL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamL", typeof(IIS.CodeReviewEngine.Team));
                }
            }
        }
    }
}
