//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Команда, в которой работает программист. Нужна для определения набора данных, которые интересны программисту.
    /// </summary>
    // *** Start programmer edit section *** (TeamForProgrammer CustomAttributes)

    // *** End programmer edit section *** (TeamForProgrammer CustomAttributes)
    [AutoAltered()]
    [Caption("Команда программиста")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TeamForProgrammerE", new string[] {
            "Team as \'Team\'",
            "Team.Name as \'Name\'"}, Hidden=new string[] {
            "Team.Name"})]
    [MasterViewDefineAttribute("TeamForProgrammerE", "Team", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class TeamForProgrammer : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CodeReviewEngine.Team fTeam;
        
        private IIS.CodeReviewEngine.TFSProgrammer fTFSProgrammer;
        
        // *** Start programmer edit section *** (TeamForProgrammer CustomMembers)

        // *** End programmer edit section *** (TeamForProgrammer CustomMembers)

        
        /// <summary>
        /// Команда, в которой работает программист. Нужна для определения набора данных, которые интересны программисту.
        /// </summary>
        // *** Start programmer edit section *** (TeamForProgrammer.Team CustomAttributes)

        // *** End programmer edit section *** (TeamForProgrammer.Team CustomAttributes)
        [PropertyStorage(new string[] {
                "Team"})]
        [NotNull()]
        public virtual IIS.CodeReviewEngine.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (TeamForProgrammer.Team Get start)

                // *** End programmer edit section *** (TeamForProgrammer.Team Get start)
                IIS.CodeReviewEngine.Team result = this.fTeam;
                // *** Start programmer edit section *** (TeamForProgrammer.Team Get end)

                // *** End programmer edit section *** (TeamForProgrammer.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TeamForProgrammer.Team Set start)

                // *** End programmer edit section *** (TeamForProgrammer.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (TeamForProgrammer.Team Set end)

                // *** End programmer edit section *** (TeamForProgrammer.Team Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CodeReviewEngine.TFSProgrammer.
        /// </summary>
        // *** Start programmer edit section *** (TeamForProgrammer.TFSProgrammer CustomAttributes)

        // *** End programmer edit section *** (TeamForProgrammer.TFSProgrammer CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Programmer"})]
        public virtual IIS.CodeReviewEngine.TFSProgrammer TFSProgrammer
        {
            get
            {
                // *** Start programmer edit section *** (TeamForProgrammer.TFSProgrammer Get start)

                // *** End programmer edit section *** (TeamForProgrammer.TFSProgrammer Get start)
                IIS.CodeReviewEngine.TFSProgrammer result = this.fTFSProgrammer;
                // *** Start programmer edit section *** (TeamForProgrammer.TFSProgrammer Get end)

                // *** End programmer edit section *** (TeamForProgrammer.TFSProgrammer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TeamForProgrammer.TFSProgrammer Set start)

                // *** End programmer edit section *** (TeamForProgrammer.TFSProgrammer Set start)
                this.fTFSProgrammer = value;
                // *** Start programmer edit section *** (TeamForProgrammer.TFSProgrammer Set end)

                // *** End programmer edit section *** (TeamForProgrammer.TFSProgrammer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TeamForProgrammerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamForProgrammerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamForProgrammerE", typeof(IIS.CodeReviewEngine.TeamForProgrammer));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of TeamForProgrammer.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfTeamForProgrammer CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfTeamForProgrammer CustomAttributes)
    public class DetailArrayOfTeamForProgrammer : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CodeReviewEngine.DetailArrayOfTeamForProgrammer members)

        // *** End programmer edit section *** (IIS.CodeReviewEngine.DetailArrayOfTeamForProgrammer members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type TeamForProgrammer by index.
        /// </summary>
        /// <summary>
        /// Adds object with type TeamForProgrammer.
        /// </summary>
        public DetailArrayOfTeamForProgrammer(IIS.CodeReviewEngine.TFSProgrammer fTFSProgrammer) : 
                base(typeof(TeamForProgrammer), ((ICSSoft.STORMNET.DataObject)(fTFSProgrammer)))
        {
        }
        
        public IIS.CodeReviewEngine.TeamForProgrammer this[int index]
        {
            get
            {
                return ((IIS.CodeReviewEngine.TeamForProgrammer)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CodeReviewEngine.TeamForProgrammer dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
