//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проект TFS для проверки.
    /// </summary>
    // *** Start programmer edit section *** (TFSProjectForReview CustomAttributes)

    // *** End programmer edit section *** (TFSProjectForReview CustomAttributes)
    [AutoAltered()]
    [Caption("Проект TFS для проверки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TFSProjectForReviewE", new string[] {
            "TFSProject as \'T f s project\'",
            "TFSProject.Name as \'Name\'"}, Hidden=new string[] {
            "TFSProject.Name"})]
    [MasterViewDefineAttribute("TFSProjectForReviewE", "TFSProject", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class TFSProjectForReview : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.CodeReviewEngine.TFSProject fTFSProject;
        
        private IIS.CodeReviewEngine.Team fTeam;
        
        // *** Start programmer edit section *** (TFSProjectForReview CustomMembers)

        // *** End programmer edit section *** (TFSProjectForReview CustomMembers)

        
        /// <summary>
        /// Проект TFS для проверки.
        /// </summary>
        // *** Start programmer edit section *** (TFSProjectForReview.TFSProject CustomAttributes)

        // *** End programmer edit section *** (TFSProjectForReview.TFSProject CustomAttributes)
        [PropertyStorage(new string[] {
                "TFSProject"})]
        [NotNull()]
        public virtual IIS.CodeReviewEngine.TFSProject TFSProject
        {
            get
            {
                // *** Start programmer edit section *** (TFSProjectForReview.TFSProject Get start)

                // *** End programmer edit section *** (TFSProjectForReview.TFSProject Get start)
                IIS.CodeReviewEngine.TFSProject result = this.fTFSProject;
                // *** Start programmer edit section *** (TFSProjectForReview.TFSProject Get end)

                // *** End programmer edit section *** (TFSProjectForReview.TFSProject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TFSProjectForReview.TFSProject Set start)

                // *** End programmer edit section *** (TFSProjectForReview.TFSProject Set start)
                this.fTFSProject = value;
                // *** Start programmer edit section *** (TFSProjectForReview.TFSProject Set end)

                // *** End programmer edit section *** (TFSProjectForReview.TFSProject Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CodeReviewEngine.Team.
        /// </summary>
        // *** Start programmer edit section *** (TFSProjectForReview.Team CustomAttributes)

        // *** End programmer edit section *** (TFSProjectForReview.Team CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Team"})]
        public virtual IIS.CodeReviewEngine.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (TFSProjectForReview.Team Get start)

                // *** End programmer edit section *** (TFSProjectForReview.Team Get start)
                IIS.CodeReviewEngine.Team result = this.fTeam;
                // *** Start programmer edit section *** (TFSProjectForReview.Team Get end)

                // *** End programmer edit section *** (TFSProjectForReview.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TFSProjectForReview.Team Set start)

                // *** End programmer edit section *** (TFSProjectForReview.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (TFSProjectForReview.Team Set end)

                // *** End programmer edit section *** (TFSProjectForReview.Team Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TFSProjectForReviewE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TFSProjectForReviewE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TFSProjectForReviewE", typeof(IIS.CodeReviewEngine.TFSProjectForReview));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of TFSProjectForReview.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfTFSProjectForReview CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfTFSProjectForReview CustomAttributes)
    public class DetailArrayOfTFSProjectForReview : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CodeReviewEngine.DetailArrayOfTFSProjectForReview members)

        // *** End programmer edit section *** (IIS.CodeReviewEngine.DetailArrayOfTFSProjectForReview members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type TFSProjectForReview by index.
        /// </summary>
        /// <summary>
        /// Adds object with type TFSProjectForReview.
        /// </summary>
        public DetailArrayOfTFSProjectForReview(IIS.CodeReviewEngine.Team fTeam) : 
                base(typeof(TFSProjectForReview), ((ICSSoft.STORMNET.DataObject)(fTeam)))
        {
        }
        
        public IIS.CodeReviewEngine.TFSProjectForReview this[int index]
        {
            get
            {
                return ((IIS.CodeReviewEngine.TFSProjectForReview)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CodeReviewEngine.TFSProjectForReview dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
