//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CodeReviewEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Программист. Данные берутся из TFS.
    /// </summary>
    // *** Start programmer edit section *** (TFSProgrammer CustomAttributes)

    // *** End programmer edit section *** (TFSProgrammer CustomAttributes)
    [AutoAltered()]
    [Caption("Программист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TFSProgrammerE", new string[] {
            "Name as \'Name\'",
            "Login as \'Login\'",
            "Domain as \'Domain\'"})]
    [AssociatedDetailViewAttribute("TFSProgrammerE", "Teams", "TeamForProgrammerE", true, "", "Teams", true, new string[] {
            ""})]
    [View("TFSProgrammerL", new string[] {
            "Name as \'Name\'",
            "Login as \'Login\'",
            "Domain as \'Domain\'"})]
    public class TFSProgrammer : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fLogin;
        
        private string fDomain;
        
        private IIS.CodeReviewEngine.DetailArrayOfTeamForProgrammer fTeams;
        
        // *** Start programmer edit section *** (TFSProgrammer CustomMembers)

        // *** End programmer edit section *** (TFSProgrammer CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (TFSProgrammer.Name CustomAttributes)

        // *** End programmer edit section *** (TFSProgrammer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (TFSProgrammer.Name Get start)

                // *** End programmer edit section *** (TFSProgrammer.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (TFSProgrammer.Name Get end)

                // *** End programmer edit section *** (TFSProgrammer.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TFSProgrammer.Name Set start)

                // *** End programmer edit section *** (TFSProgrammer.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (TFSProgrammer.Name Set end)

                // *** End programmer edit section *** (TFSProgrammer.Name Set end)
            }
        }
        
        /// <summary>
        /// Логин.
        /// </summary>
        // *** Start programmer edit section *** (TFSProgrammer.Login CustomAttributes)

        // *** End programmer edit section *** (TFSProgrammer.Login CustomAttributes)
        [StrLen(255)]
        public virtual string Login
        {
            get
            {
                // *** Start programmer edit section *** (TFSProgrammer.Login Get start)

                // *** End programmer edit section *** (TFSProgrammer.Login Get start)
                string result = this.fLogin;
                // *** Start programmer edit section *** (TFSProgrammer.Login Get end)

                // *** End programmer edit section *** (TFSProgrammer.Login Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TFSProgrammer.Login Set start)

                // *** End programmer edit section *** (TFSProgrammer.Login Set start)
                this.fLogin = value;
                // *** Start programmer edit section *** (TFSProgrammer.Login Set end)

                // *** End programmer edit section *** (TFSProgrammer.Login Set end)
            }
        }
        
        /// <summary>
        /// Домен.
        /// </summary>
        // *** Start programmer edit section *** (TFSProgrammer.Domain CustomAttributes)

        // *** End programmer edit section *** (TFSProgrammer.Domain CustomAttributes)
        [StrLen(255)]
        public virtual string Domain
        {
            get
            {
                // *** Start programmer edit section *** (TFSProgrammer.Domain Get start)

                // *** End programmer edit section *** (TFSProgrammer.Domain Get start)
                string result = this.fDomain;
                // *** Start programmer edit section *** (TFSProgrammer.Domain Get end)

                // *** End programmer edit section *** (TFSProgrammer.Domain Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TFSProgrammer.Domain Set start)

                // *** End programmer edit section *** (TFSProgrammer.Domain Set start)
                this.fDomain = value;
                // *** Start programmer edit section *** (TFSProgrammer.Domain Set end)

                // *** End programmer edit section *** (TFSProgrammer.Domain Set end)
            }
        }
        
        /// <summary>
        /// Программист. Данные берутся из TFS.
        /// </summary>
        // *** Start programmer edit section *** (TFSProgrammer.Teams CustomAttributes)

        // *** End programmer edit section *** (TFSProgrammer.Teams CustomAttributes)
        public virtual IIS.CodeReviewEngine.DetailArrayOfTeamForProgrammer Teams
        {
            get
            {
                // *** Start programmer edit section *** (TFSProgrammer.Teams Get start)

                // *** End programmer edit section *** (TFSProgrammer.Teams Get start)
                if ((this.fTeams == null))
                {
                    this.fTeams = new IIS.CodeReviewEngine.DetailArrayOfTeamForProgrammer(this);
                }
                IIS.CodeReviewEngine.DetailArrayOfTeamForProgrammer result = this.fTeams;
                // *** Start programmer edit section *** (TFSProgrammer.Teams Get end)

                // *** End programmer edit section *** (TFSProgrammer.Teams Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TFSProgrammer.Teams Set start)

                // *** End programmer edit section *** (TFSProgrammer.Teams Set start)
                this.fTeams = value;
                // *** Start programmer edit section *** (TFSProgrammer.Teams Set end)

                // *** End programmer edit section *** (TFSProgrammer.Teams Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TFSProgrammerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TFSProgrammerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TFSProgrammerE", typeof(IIS.CodeReviewEngine.TFSProgrammer));
                }
            }
            
            /// <summary>
            /// "TFSProgrammerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TFSProgrammerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TFSProgrammerL", typeof(IIS.CodeReviewEngine.TFSProgrammer));
                }
            }
        }
    }
}
