/*flexberryautogenerated="true"*/
namespace IIS.CodeReviewEngine
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class TeamL : BaseListForm<Team>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public TeamL() : base(Team.Views.TeamL)
        {
            EditPage = TeamE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Team/TeamL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
