//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить выбранные.
        /// </summary>
        internal static string Add_Selected {
            get {
                return ResourceManager.GetString("Add_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение отображения колонок....
        /// </summary>
        internal static string Change_Columns_View {
            get {
                return ResourceManager.GetString("Change_Columns_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан параметр.
        /// </summary>
        internal static string ChooseColumns_Parameter_is_required {
            get {
                return ResourceManager.GetString("ChooseColumns_Parameter_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для управления порядком столбцов зажмите левую кнопку мыши на названии столбца и
        ///            переместите курсор.
        ///            &lt;br /&gt;
        ///            Для управления видимостью столбца поставьте/снимите соответствующую галочку..
        /// </summary>
        internal static string Choose_Columns_Hint {
            get {
                return ResourceManager.GetString("Choose_Columns_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить условия фильтрации.
        /// </summary>
        internal static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить отображение столбцов.
        /// </summary>
        internal static string Columns_Configure {
            get {
                return ResourceManager.GetString("Columns_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название столбца.
        /// </summary>
        internal static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  содержат.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла критическая ошибка. Нажмите кнопку «Назад» в браузере и попробуйте ещё раз..
        /// </summary>
        internal static string Crirical_Error {
            get {
                return ResourceManager.GetString("Crirical_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить сортировку по умолчанию.
        /// </summary>
        internal static string DefaultSort {
            get {
                return ResourceManager.GetString("DefaultSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        internal static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробно ».
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображаемая ошибка:.
        /// </summary>
        internal static string Displayed_Error {
            get {
                return ResourceManager.GetString("Displayed_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан EditPage (форма редактирования) для WebObjectListView.
        /// </summary>
        internal static string EditPageWolvNotFound {
            get {
                return ResourceManager.GetString("EditPageWolvNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string Error_Occurred {
            get {
                return ResourceManager.GetString("Error_Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в Excel.
        /// </summary>
        internal static string Export_Excel {
            get {
                return ResourceManager.GetString("Export_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в XML.
        /// </summary>
        internal static string Export_XML {
            get {
                return ResourceManager.GetString("Export_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтрация.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; Copyright MyCorp.
        /// </summary>
        internal static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при обработке формы.
        /// </summary>
        internal static string Form_Error {
            get {
                return ResourceManager.GetString("Form_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовая страница.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная дата.
        /// </summary>
        internal static string Incorrect_Date {
            get {
                return ResourceManager.GetString("Incorrect_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница:.
        /// </summary>
        internal static string LabelPage {
            get {
                return ResourceManager.GetString("LabelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный логин или пароль. Попробуйте еще раз..
        /// </summary>
        internal static string LoginUser_FailureText {
            get {
                return ResourceManager.GetString("LoginUser.FailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        internal static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка {0} строк может занять длительное время. Продолжить?.
        /// </summary>
        internal static string LongTimeStringExport {
            get {
                return ResourceManager.GetString("LongTimeStringExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookUp.
        /// </summary>
        internal static string Lookup_Title {
            get {
                return ResourceManager.GetString("Lookup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Название проекта].
        /// </summary>
        internal static string Master_Page_Header_Title {
            get {
                return ResourceManager.GetString("Master_Page_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web system on CASEBERRY Technology.
        /// </summary>
        internal static string Master_Page_Title {
            get {
                return ResourceManager.GetString("Master_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть меню.
        /// </summary>
        internal static string Menu_Hide {
            get {
                return ResourceManager.GetString("Menu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать меню.
        /// </summary>
        internal static string Menu_Show {
            get {
                return ResourceManager.GetString("Menu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать на основе.
        /// </summary>
        internal static string New_on_Basis {
            get {
                return ResourceManager.GetString("New_on_Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее ».
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Были удалены не все объекты, т.к. некоторые объекты были заблокированы. .
        /// </summary>
        internal static string NotAllObjRemoved {
            get {
                return ResourceManager.GetString("NotAllObjRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        internal static string No_Data {
            get {
                return ResourceManager.GetString("No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено объектов:.
        /// </summary>
        internal static string ObjRemoveCount {
            get {
                return ResourceManager.GetString("ObjRemoveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка удаления объекта.
        /// </summary>
        internal static string ObjRemoveError {
            get {
                return ResourceManager.GetString("ObjRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Назад.
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно для заполнения.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить порядок по умолчанию.
        /// </summary>
        internal static string Reset_Sort {
            get {
                return ResourceManager.GetString("Reset_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты {0} &amp;ndash; {1} из {2}.
        /// </summary>
        internal static string Results0to1of2 {
            get {
                return ResourceManager.GetString("Results0to1of2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результатов: .
        /// </summary>
        internal static string ResultsCount {
            get {
                return ResourceManager.GetString("ResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество результатов на странице: .
        /// </summary>
        internal static string ResultsOnPage {
            get {
                return ResourceManager.GetString("ResultsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и закрыть.
        /// </summary>
        internal static string Save_Close {
            get {
                return ResourceManager.GetString("Save_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при сохранении и закрытии.
        /// </summary>
        internal static string Save_Close_Error {
            get {
                return ResourceManager.GetString("Save_Close_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить строку поиска.
        /// </summary>
        internal static string Search_Clear_Text {
            get {
                return ResourceManager.GetString("Search_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что искать.
        /// </summary>
        internal static string Search_What {
            get {
                return ResourceManager.GetString("Search_What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где искать.
        /// </summary>
        internal static string Search_Where {
            get {
                return ResourceManager.GetString("Search_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить все на всех страницах.
        /// </summary>
        internal static string SelectAllObjOnAllPages {
            get {
                return ResourceManager.GetString("SelectAllObjOnAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить все.
        /// </summary>
        internal static string SelectAllObjOnPage {
            get {
                return ResourceManager.GetString("SelectAllObjOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите значение.
        /// </summary>
        internal static string Select_Value {
            get {
                return ResourceManager.GetString("Select_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показаны строки у которых поля.
        /// </summary>
        internal static string ShowingRowsWhoseFields {
            get {
                return ResourceManager.GetString("ShowingRowsWhoseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Показано с {0} по {1} из {2}).
        /// </summary>
        internal static string Shown0to1from2 {
            get {
                return ResourceManager.GetString("Shown0to1from2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будут выгружены только первые 10000 строк. Продолжить?.
        /// </summary>
        internal static string StringExportFirst10K {
            get {
                return ResourceManager.GetString("StringExportFirst10K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставить/Снять отметки.
        /// </summary>
        internal static string Switch_Checkboxes {
            get {
                return ResourceManager.GetString("Switch_Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы применить фильтр, введите значение и нажмите: .
        /// </summary>
        internal static string Tooltip_FilterApply {
            get {
                return ResourceManager.GetString("Tooltip_FilterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Символ &lt;b&gt;*&lt;/b&gt; при поиске (фильтрации) означает любое количество любых символов.
        /// </summary>
        internal static string Tooltip_FilterApply2 {
            get {
                return ResourceManager.GetString("Tooltip_FilterApply2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для перехода на произвольную страницу введите номер страницы и нажмите клавишу Enter.
        /// </summary>
        internal static string Tooltip_PageNumInput {
            get {
                return ResourceManager.GetString("Tooltip_PageNumInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть область переходов.
        /// </summary>
        internal static string Tree_View_Hide {
            get {
                return ResourceManager.GetString("Tree_View_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отобразить область переходов.
        /// </summary>
        internal static string Tree_View_Show {
            get {
                return ResourceManager.GetString("Tree_View_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View не инициализировано.
        /// </summary>
        internal static string View_Not_Initialize {
            get {
                return ResourceManager.GetString("View_Not_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заданы неправильные параметры при открытии формы. Пожалуйста, нажмите кнопку назад в браузере и повторите попытку..
        /// </summary>
        internal static string Wrong_Form_Params {
            get {
                return ResourceManager.GetString("Wrong_Form_Params", resourceCulture);
            }
        }
    }
}
