<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ApplicationLogL.aspx.cs" Inherits="IIS.Flexberry.ApplicationLogL" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-list">
        <h2 class="ics-form-header ics-header-listform">Application Log</h2>
        <div class="ics-form-controls ics-form-controls-list">
            <ac:WebObjectListView ID="WebObjectListView1" runat="server" Visible="true" />
        </div>
    </div>
</asp:Content>
<%-- Autogenerated section start [Register] --%>
<%--<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>--%>
<%-- Autogenerated section end [Register] --%>
