/*flexberryautogenerated="true"*/
namespace IIS.Flexberry
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using IIS.Caseberry.Logging.Objects;

    using Resources;

    public partial class ApplicationLogL : BaseListForm<ApplicationLog>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ApplicationLogL()
            : base(ApplicationLog.Views.ApplicationLogL)
        {
            EditPage = ApplicationLogE.FormPath;
        }

        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/ApplicationLog/ApplicationLogL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
