<%--flexberryautogenerated="true"--%>

<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ApplicationLogE.aspx.cs" Inherits="IIS.Flexberry.ApplicationLogE" %>

<%-- Autogenerated section start [Register] --%>
<%--<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>--%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-edit">
        <h2 class="ics-form-header ics-form-header-edit">Application Log Event</h2>
        <div class="ics-form-toolbar ics-form-toolbar-edit ics-sticky">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="ics-form-controls ics-form-controls-edit">
            <%-- Autogenerated section start [Controls] --%>
            <!-- autogenerated start -->
            <div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlEventIdLabel" runat="server" Text="EventId" EnableViewState="False">
                    </asp:Label>
                    <asp:Label CssClass="descTxt" ID="ctrlEventId" runat="server">
                    </asp:Label>

                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlTimestampLabel" runat="server" Text="Timestamp" EnableViewState="False">
                    </asp:Label>
                    <asp:Label class="descTxt" ID="ctrlTimestamp" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlThreadNameLabel" runat="server" Text="ThreadName" EnableViewState="False">
                    </asp:Label>
                    <asp:Label CssClass="descTxt" ID="ctrlThreadName" runat="server">
                    </asp:Label>

                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlCategoryLabel" runat="server" Text="Category" EnableViewState="False">
                    </asp:Label>
                    <asp:Label CssClass="descTxt" ID="ctrlCategory" runat="server">
                    </asp:Label>

                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlProcessNameLabel" runat="server" Text="ProcessName" EnableViewState="False">
                    </asp:Label>
                    <asp:Label CssClass="descTxt" ID="ctrlProcessName" runat="server">
                    </asp:Label>

                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlMessageLabel" runat="server" Text="Message" EnableViewState="False">
                    </asp:Label>
                    <asp:Label CssClass="descTxt" ID="ctrlMessage" runat="server">
                    </asp:Label>

                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlFormattedMessageLabel" runat="server" Text="FormattedMessage" EnableViewState="False">
                    </asp:Label>
                    <asp:Label CssClass="descTxt" ID="ctrlFormattedMessage" runat="server">
                    </asp:Label>

                </div>
                <br />

            </div>
            <!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
