<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="TFSProjectL.aspx.cs" Inherits="IIS.CodeReviewEngine.TFSProjectL" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-list">
        <h2 class="ics-form-header ics-header-listform">T f s project</h2>
        <div class="ics-form-controls ics-form-controls-list">
            <ac:WebObjectListView ID="WebObjectListView1" runat="server" Visible="true" />
        </div>
    </div>
</asp:Content>
