/*flexberryautogenerated="true"*/
namespace IIS.CodeReviewEngine
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class TFSProjectL : BaseListForm<TFSProject>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public TFSProjectL() : base(TFSProject.Views.TFSProjectL)
        {
            EditPage = TFSProjectE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/TFSProject/TFSProjectL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
