/*flexberryautogenerated="true"*/
namespace IIS.CodeReviewEngine
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class TeamSliceL : BaseListForm<TeamSlice>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public TeamSliceL() : base(TeamSlice.Views.TeamSliceL)
        {
            EditPage = TeamSliceE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/TeamSlice/TeamSliceL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
