<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="TeamSliceE.aspx.cs" Inherits="IIS.CodeReviewEngine.TeamSliceE" %>

<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-edit">
        <h2 class="ics-form-header ics-form-header-edit">Team slice</h2>
        <div class="ics-form-toolbar ics-form-toolbar-edit ics-sticky">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="ics-form-controls ics-form-controls-edit">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlStartDateLabel" runat="server" Text="Start date" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlStartDate" runat="server"/>
</div>
<ac:Hinter ID="ctrlStartDateHint" runat="server" Title="Начальная дата, границы включаются."/>
<asp:RequiredFieldValidator ID="ctrlStartDateValidator" runat="server" ControlToValidate="ctrlStartDate"
ErrorMessage="Не указано: StartDate" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlEndDateLabel" runat="server" Text="End date" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlEndDate" runat="server"/>
</div>
<ac:Hinter ID="ctrlEndDateHint" runat="server" Title="Конечная дата, границы включаются."/>
<asp:RequiredFieldValidator ID="ctrlEndDateValidator" runat="server" ControlToValidate="ctrlEndDate"
ErrorMessage="Не указано: EndDate" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTeamLabel" runat="server" Text="Team" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlTeam" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlTeamValidator" runat="server" ControlToValidate="ctrlTeam"
ErrorMessage="Не указано: Team" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<asp:ScriptManager ID="ScriptManager1" runat="server" >
</asp:ScriptManager>

<br/>
<fieldset ID="ctrl_fsReviewers" style="clear: left">
	<legend>Reviewers</legend>
	<div style="clear: left">
	<ac:AjaxGroupEdit ID="ctrlReviewers" runat="server" ReadOnly="false" />
</div>

</fieldset>
</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
