<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="RoleE.aspx.cs" Inherits="IIS.Product_19312.RoleE" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
Роль
<br/>
    <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="Сохранить" ValidationGroup="savedoc" />
    <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="Сохранить и закрыть" ValidationGroup="savedoc" />
    <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="Отмена" />
<br/>

<!-- autogenerated start -->
<div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlNameLabel" runat="server" Text="Имя роли" EnableViewState="False">
	</asp:Label>
	<asp:TextBox CssClass="descTxt" ID="ctrlName" runat="server">
	</asp:TextBox>
	</div>
    
    <div class="clearfix">
        <asp:Label CssClass="descLbl" runat="server" Text="Родительские роли" EnableViewState="False"></asp:Label>

        <asp:Table ID="tblParentRoles" CssClass="descTxt" runat="server"
                   BorderWidth="1">
        </asp:Table>
    </div>
    
    <div class="clearfix">
        <asp:Label CssClass="descLbl" runat="server" Text="Пользователи" EnableViewState="False"></asp:Label>

        <asp:Table ID="tblRoleUsers" CssClass="descTxt" runat="server"
                   BorderWidth="1">
        </asp:Table>
    </div>
    
    <div class="clearfix">
        <asp:Label CssClass="descLbl" runat="server" Text="Классы" EnableViewState="False"></asp:Label>

        <asp:Table ID="tblRoleClasses" CssClass="descTxt" runat="server"
                   BorderWidth="1">
        </asp:Table>
    </div>
  
  <%--
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlLoginLabel" runat="server" Text="Логин" EnableViewState="False">
	</asp:Label>
	<asp:TextBox CssClass="descTxt" ID="ctrlLogin" runat="server">
	</asp:TextBox>
	</div>

	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlPwdLabel" runat="server" Text="Пароль" EnableViewState="False">
	</asp:Label>
	<asp:TextBox CssClass="descTxt" ID="ctrlPassword" runat="server">
	</asp:TextBox>
	
	</div>
	
  <div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlIsUserLabel" runat="server" Text="Is user" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlIsUser" CssClass="descTxt" runat="server" Text=""/>
	</div>

	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlIsGroupLabel" runat="server" Text="Is group" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlIsGroup" CssClass="descTxt" runat="server" Text=""/>
	</div>

	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlIsRoleLabel" runat="server" Text="Is role" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlIsRole" CssClass="descTxt" runat="server" Text=""/>
	</div>

	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlConnStringLabel" runat="server" Text="Conn string" EnableViewState="False">
	</asp:Label>
	<asp:TextBox CssClass="descTxt" ID="ctrlConnString" runat="server">
	</asp:TextBox>
	
	</div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlEnabledLabel" runat="server" Text="Enabled" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlEnabled" CssClass="descTxt" runat="server" Text=""/>
	</div>

	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlFullLabel" runat="server" Text="Full" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlFull" CssClass="descTxt" runat="server" Text=""/>
	</div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlReadLabel" runat="server" Text="Read" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlRead" CssClass="descTxt" runat="server" Text=""/>
	</div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlInsertLabel" runat="server" Text="Insert" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlInsert" CssClass="descTxt" runat="server" Text=""/>
	</div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlUpdateLabel" runat="server" Text="Update" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlUpdate" CssClass="descTxt" runat="server" Text=""/>
	</div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlDeleteLabel" runat="server" Text="Delete" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlDelete" CssClass="descTxt" runat="server" Text=""/>
	</div>
	<div class="clearfix">
	<asp:Label CssClass="descLbl" ID="ctrlExecuteLabel" runat="server" Text="Execute" EnableViewState="False">
	</asp:Label>
	<asp:CheckBox ID="ctrlExecute" CssClass="descTxt" runat="server" Text=""/>
	</div>--%>

</div>
<!-- autogenerated end -->

</asp:Content>